{
 "title": "API_Classic_Usage_by_Category",
 "time": { "from": "2025-04-25T07:00:00.000Z", "to": "2025-04-26T06:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   { "name": "user", "query": "dabella.com" },
   { "name": "jurisdiction", "query": "us,ca,eu,uk" }
  ]
 },
 "panels": [
  {
   "title": "UPLOAD_SINGLE USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `addRecordToList` or `deleteRecordFromList` or `updateCrmRecord` !=`Response` or `async` or `w2c` | json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "UPLOAD USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}`|= `addToList`  \r\nor `deleteAllFromList`  \r\nor `deleteFromContacts`  \r\nor `deleteFromList`  \r\nor `updateContacts`  \r\nor `updateDispositions`  \r\n\r\n!=`Response`| json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "REPORT USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `getAgentAuditReport` or `getCallLogReport` or `runReport` != `Result` !=`Response` | json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "RETRIEVE_REPORT USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `getReportResult` !=`Response` | json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "ASYNC_UPLOAD USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `async` !=`Response` | json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "MODIFY USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `acceptChatInvite` \r\nor `addDispositionsToCampaign` \r\nor `addDNISToCampaign` \r\nor `addListsToCampaign` \r\nor `addNumbersToDnc` \r\nor `addPromptTTS` \r\nor `addPromptWav` \r\nor `addPromptWavInline` \r\nor `addSkillsToCampaign` \r\nor `closeChatSession` \r\nor `createAgentGroup` \r\nor `createAutodialCampaign` \r\nor `createCallVariable` \r\nor `createCallVariablesGroup` \r\nor `createCampaignProfile` \r\nor `createChatSession` \r\nor `createContactField` \r\nor `createDisposition` \r\nor `createInboundCampaign` \r\nor `createIVRScript` \r\nor `createList` \r\nor `createOutboundCampaign` \r\nor `createReasonCode` \r\nor `createSkill` \r\nor `createSpeedDialNumber` \r\nor `createUser` \r\nor `createUserProfile` \r\nor `createWebConnector` \r\nor `deleteAgentGroup` \r\nor `deleteCallVariable` \r\nor `deleteCallVariablesGroup` \r\nor `deleteCampaign` \r\nor `deleteCampaignProfile` \r\nor `deleteContactField` \r\nor `deleteIVRScript` \r\nor `deleteList` \r\nor `deletePrompt` \r\nor `deleteReasonCode` \r\nor `deleteReasonCodeByType` \r\nor `deleteSkill` \r\nor `deleteUser` \r\nor `deleteUserProfile` \r\nor `deleteWebConnector` \r\nor `forceStopCampaign` \r\nor `getDispositionsNames` \r\nor `getLoggedInUsers` \r\nor `getMyGroupIds` \r\nor `getMyPermissions` \r\nor `getMySkillsIds` \r\nor `loginStation` \r\nor `modifyAgentGroup` \r\nor `modifyAutodialCampaign` \r\nor `modifyCallVariable` \r\nor `modifyCallVariablesGroup` \r\nor `modifyCampaignLists` \r\nor `modifyCampaignProfile` \r\nor `modifyCampaignProfileCrmCriteria` \r\nor `modifyCampaignProfileDispositions` \r\nor `modifyCampaignProfileFilterOrder` \r\nor `modifyContactField` \r\nor `modifyDisposition` \r\nor `modifyInboundCampaign` \r\nor `modifyIVRScript` \r\nor `modifyOutboundCampaign` \r\nor `modifyPromptTTS` \r\nor `modifyPromptWav` \r\nor `modifyPromptWavInline` \r\nor `modifyReasonCode` \r\nor `modifySkill` \r\nor `modifyUser` \r\nor `modifyUserCannedReports` \r\nor `modifyUserProfileSkills` \r\nor `modifyUserProfileUserList` \r\nor `modifyVCCConfiguration` \r\nor `modifyWebConnector` \r\nor `receiveMessages` \r\nor `reconnectStation` \r\nor `removeDisposition` \r\nor `removeDispositionsFromCampaign` \r\nor `removeDNISFromCampaign` \r\nor `removeListsFromCampaign` \r\nor `removeNumbersFromDnc` \r\nor `removeSkillsFromCampaign` \r\nor `removeSpeedDialNumber` \r\nor `removeUserFromChat` \r\nor `renameCampaign` \r\nor `renameDisposition` \r\nor `resetCampaign` \r\nor `resetCampaignDispositions` \r\nor `resetListPosition` \r\nor `sendBroadcastMessages` \r\nor `sendChatInvite` \r\nor `sendInfoMessage` \r\nor `sendMsgToChat` \r\nor `setDefaultIVRSchedule` \r\nor `setDialingRules` \r\nor `setSkillVoicemailGreeting` \r\nor `setUserVoicemailGreeting` \r\nor `startCampaign` \r\nor `startMonitoring` \r\nor `stopCampaign` \r\nor `stopMonitoring` \r\nor `userSkillAdd` \r\nor `userSkillModify` \r\nor `userSkillRemove` \r\n\r\n!=`Response` | json | logType = `vcc_apife_logs` [1m])) "
    }
   ]
  },
  {
   "title": "QUERY_CHANGED_STAT USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}`  |= `getStatisticsUpdate` !=`Response` | json | logType = `vcc_apife_logs` [1m]))"
    }
   ]
  },
  {
   "title": "QUERY_STAT USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `getColumnNames` or `getStatistics` or `setSessionParameters` !=`Response` or `getStatisticsUpdate` | json | logType = `vcc_apife_logs` [1m]))"
    }
   ]
  },
  {
   "title": "QUERY USE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(minute) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `${user}` |= `getSkill`  \r\nor `getAgent`  \r\nor `getCall`  \r\nor `getAutodialCampaign`  \r\nor `getCampaign`  \r\nor `getContact`  \r\nor `getCrmImportResult`  \r\nor `getDialingRules`  \r\nor `getDisposition`  \r\nor `getDNISList`  \r\nor `getInboundCampaign`  \r\nor `getIVRScripts`  \r\nor `getList`  \r\nor `getMonitoringSupervisors`  \r\nor `getOutboundCampaign`  \r\nor `getPrompt`  \r\nor `getReasonCode`  \r\nor `getReasonCodeByType`  \r\nor `getSessionParameters`  \r\nor `getSpeedDialNumbers`  \r\nor `getUser`  \r\nor `getVCCConfiguration`  \r\nor `getWebConnectors` \r\nor `checkDncForNumbers` \r\nor `closeSession`\r\nor `isImportRunning`\r\nor `isReportRunning`\r\n\r\n!=`Response` | json | logType = `vcc_apife_logs` [1m]))"
    }
   ]
  }
 ]
}