{
 "title": "API_Google_Limits_Hour",
 "description": "API Limits for Google Datacenters by Hour",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DomainID", "label": "Domain ID" },
   {
    "name": "DomainID_Filter",
    "query": "${DomainID:regex,/^(\\d+)$/,'\"\\1\"'}"
   },
   { "name": "jurisdiction", "query": "us,ca,uk,eu" },
   { "name": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "API ASYNC_UPLOAD Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `ASYNC_UPLOAD` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API RETRIEVE_REPORT Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `RETRIEVE_REPORT` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API MODIFY Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `MODIFY` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API UPLOAD Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | json | logType = `vcc_api_logs` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `UPLOAD` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API QUERY Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `QUERY` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API UPLOAD_SINGLE Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `UPLOAD_SINGLE` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API QUERY_CHANGED_STAT Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | json | logType = `vcc_api_logs` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `QUERY_CHANGED_STAT` | time = `3600` |domainid=~`${DomainID_Filter}`[1m]))"
    }
   ]
  },
  {
   "title": "API VIVR_CREATE_SESSION Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `VIVR_CREATE_SESSION` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API QUERY_STAT Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `QUERY_STAT` | time = `3600` |domainid=~`${DomainID_Filter}` [1m]))"
    }
   ]
  },
  {
   "title": "API W2C_UPLOAD Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `W2C_UPLOAD` | time = `3600` |domainid=~`${DomainID_Filter}`  [1m]))"
    }
   ]
  },
  {
   "title": "API REPORT Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(domainid, category, time) (count_over_time({service_name=\"vcc\", jurisdiction=\"${jurisdiction}\", role=\"api\"} |= `Operation ` |= `limit ` |= `exceeded for timeout` | regexp `domainId\\s=\\s(?P<domainid>\\d+)].*Operation\\s\\((?P<category>.*)\\)\\slimit\\s\\((?P<exceeded>\\d+)\\).*timeout\\s(?P<time>\\d+)` | category = `REPORT` | time = `3600` |domainid=~`${DomainID_Filter}`  [1m]))"
    }
   ]
  }
 ]
}